[workspace]
members = [
    "core",
    "host",
    "system",
    "resource",
    "experimental/binding",
    "experimental/projection",
    "experimental/resource-registry",
    "component",
    "sdk",
    "sdk-macros",
    "tests/raw-api",
    "tests/sdk-api",
    "tests/docs-getting-started",
    "tests/extensions/resource-clock",
    "tests/extensions/resource-counter",
    "tests/extensions/system-operations",
    "tests/extensions/adapter-clock-memory",
    "tests/extensions/adapter-external",
    "tests/extensions/component-greeter",
    "tests/external-extension",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/Onoal/fabric"

[workspace.dependencies]
fabric-host = { package = "onoal-fabric-host", version = "0.1.0", path = "host" }
fabric-core = { package = "onoal-fabric-core", version = "0.1.0", path = "core" }
fabric-resource = { package = "onoal-fabric-resource", version = "0.1.0", path = "resource" }
fabric-system = { package = "onoal-fabric-system", version = "0.1.0", path = "system" }
fabric-component = { package = "onoal-fabric-component", version = "0.1.0", path = "component" }
fabric-sdk-macros = { package = "onoal-fabric-sdk-macros", version = "0.1.1", path = "sdk-macros" }
fabric = { package = "onoal-fabric", version = "0.1.1", path = "sdk" }
