[package]
name = "onoal-fabric-system"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/onoal-fabric-system"
description = "Instance-wide System semantics for Fabric."
readme = "README.md"
publish = ["crates-io"]

[lib]
name = "fabric_system"

[dependencies]
semver = "1.0.27"
thiserror = "2.0.20"
