[package]
name = "third-party-augmentation-app"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
fabric = { package = "onoal-fabric", git = "https://github.com/Onoal/fabric.git", rev = "d1a0db65337439cb658702dcce3e4fb07ab71a99" }
third-party-base-semantics = { path = "../base-semantics" }
third-party-augmentation-semantics = { path = "../augmentation-semantics" }
third-party-augmentation-support = { path = "../augmentation-support" }
third-party-augmentation-consumers = { path = "../consumers" }
futures = "0.3"
