[package]
name = "onoal-fabric-resource"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/onoal-fabric-resource"
description = "Occurrence-based Resource semantics for Fabric."
readme = "README.md"
publish = ["crates-io"]

[lib]
name = "fabric_resource"

[dependencies]
semver = "1.0.27"
sha2 = "0.10.9"
thiserror = "2.0.20"
