[package]
name = "onoal-fabric"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/onoal-fabric"
description = "Ergonomic Rust SDK for composing and operating Fabric systems."
readme = "README.md"
publish = ["crates-io"]

[lib]
name = "fabric"

[dependencies]
fabric-component.workspace = true
fabric-core.workspace = true
fabric-host.workspace = true
fabric-resource.workspace = true
fabric-system.workspace = true
fabric-sdk-macros.workspace = true
thiserror = "2.0.20"
